export default {
  dateLocale: {
    days: ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"],
    daysShort: ["Min", "Sen", "Sel", "Rab", "Kam", "Jum", "Sab"],
    months: [
      "Januari",
      "Februari",
      "Maret",
      "April",
      "Mei",
      "Juni",
      "Juli",
      "Agustus",
      "September",
      "Oktober",
      "November",
      "Desember",
    ],
    monthsShort: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "Mei",
      "Jun",
      "Jul",
      "Ags",
      "Sep",
      "Okt",
      "Nov",
      "Des",
    ],
  },
  dateFormatService: "YYYY-MM-DD",
  dateFormatUI: "YYYY/MM/DD",
  timeout: 180, // in seconds,
  dateESBFormatService: "ddmmyyyy",
  timeoutMessage: "Maximum connection time exceeded",
  unknownHostPrint: "Host Print Tidak Ditemukan",
  feeUpperLimit: 50000,
  messageGeneralErrorMonetary:
    "Transaksi gagal diproses. Silakan cek rekening koran.",
  MSG_ERR_ESB: "Maaf sedang ada gangguan, mohon coba beberapa saat lagi",
};
